
version: 2.1
orbs:
  sam: circleci/aws-sam-serverless@1.0.1
jobs:
  build:
    docker:
      - image: circleci/python
        environment:
          TZ: Asia/Tokyo
          PYTHONPATH: /home/circleci/project/
    steps:
      - run:
          name: this is build test
          command: |
            echo "this is build test"
      - run:
          name: ls
          command: |
            ls -latr
  deploy_dev:
    docker:
    executor: sam/default
    steps:
      - run:
          name: ls
          command: ls -latr
      - run:
          name: print export path
          command: echo $PATH
      - run:
          name: brew ireru
          command: |
            curl -fsSL "https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh" | bash
            /home/linuxbrew/.linuxbrew/bin/brew shellenv >> $BASH_ENV
      - run:
          name: brew aws cli
          command: |
            brew --version
            brew tap aws/tap
            brew install aws-sam-cli@1.1.0
      # - run:
      #     name: nekosan
      #     command: |
      #       echo 'export PATH=/home/linuxbrew/.linuxbrew/opt/python@3.7/bin:$PATH' >> $BASH_ENV
      #       echo 'export LDFLAGS="-L/home/linuxbrew/.linuxbrew/opt/python@3.7/lib"' >> $BASH_ENV
      #       echo 'export CPPFLAGS="-I/home/linuxbrew/.linuxbrew/opt/python@3.7/include"' >> $BASH_ENV
      #       echo 'export PKG_CONFIG_PATH="/home/linuxbrew/.linuxbrew/opt/python@3.7/lib/pkgconfig"' >> $BASH_ENV
      # - run:
      #     name: print export path
      #     command: |
      #       echo $PATH
      #       echo $LDFLAGS
      #       echo $CPPFLAGS
      #       echo $PKG_CONFIG_PATH
      - checkout
      - run:
          name: aws check
          command: |
            # ls -latr /home/linuxbrew/
            # ls -latr /home/linuxbrew/.linuxbrew/
            # ls -latr /home/linuxbrew/.linuxbrew/Cellar/
            # ls -latr /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli
            # ls -latr /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.2.0
            sam --version
      - run:
          name: completed!
          command: |
            echo "omedetou- nyan"
workflows:
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - feature/add_sam_install
      - deploy_dev:
          context: sam-cli-test
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - feature/add_sam_install
