
version: 2.1
orbs:
  sam: circleci/aws-sam-serverless@1.0.1
jobs:
  build:
    docker:
      - image: circleci/python
        environment:
          TZ: Asia/Tokyo
          PYTHONPATH: /home/circleci/project/
    steps:
      - run:
          name: this is build test
          command: |
            echo "this is build test"
      - run:
          name: ls
          command: |
            ls -latr
  deploy_dev:
    docker:
    executor: sam/default
    steps:
      - checkout
      - run:
          name: sam version
          command: sam --version
workflows:
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - feature/add_sam_install
      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - feature/add_sam_install
